version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  complex:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s (%(filename)s:%(lineno)d)"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO #ERROR #CRITICAL #INFO
    formatter: simple
  logfile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG #DEBUG #INFO
    formatter: complex
    filename: /tmp/invoice_recognition.log
    maxBytes: 10485760 # 10MB
    backupCount: 2

root:
  level: INFO #DEBUG
  handlers: [console, logfile]
